# VARIABLES
month = input("Enter a month: ")
verb1 = input("Enter a verb: ")
place1 = input("Enter a place: ")
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
place2 = input("Enter a place: ")
verb2 = input("Enter a verb: ")
noun1 = input("Enter a noun: ")
verb3 = input("Enter a verb: ")
noun2 = input("Enter a noun: ")
adjective3 = input("Enter an adjective: ")
adjective4 = input("Enter an adjective: ")
color = input("Enter a color: ")
adjective5 = input("Enter an adjective: ")
verb4 = input("Enter a verb: ")
verb5 = input("Enter a verb: ")
noun3 = input("Enter a noun: ")
exclamation = input("Enter an exclamation: ")
holiday = input("Enter a holiday: ")

# Story
print("Every " + month + " we " + verb1 + " to a tree at " + place1 + " far away.")
print("Not just any " + adjective1 + " farm, a " + adjective2 + " tree at " + place2 + ".")
print("My Dad and I " + verb2 + " onto the " + noun1 + " to " + verb3 + " for the perfect " + noun2 + ".")
print("Some people like them " + adjective3 + " and " + adjective4 + " and some like them " + color + " and fat.")
print("We are searching for a tall and " + adjective5 + " one!")
print("\"Over there!\" I exclaim, \"Dad it's over there!\"")
print("Off we " + verb3 + ", saw in hand to " + verb4 + " this year's " + noun3 + " down.")
print(exclamation + " it's " + holiday + " finally!")
