#VARIABLES
food1 = input("Enter a food: ")
drink1 = input("Enter a drink: ")
obj1 = input("Enter an object: ")
Adam_Hair = input("Enter a noun: ")
noun1 = input("Enter a noun: ")
drink2 = input("Enter a drink: ")
verb1 = input("Enter a verb: ")
adj1 = input("Enter an adjective ending in -ed: ")
plural_insult = input("Enter a plural insult: ")
food2 = input("Enter a food: ")
obj2 = input("Enter an object: ")
obj3 = input("Enter a gross item: ")
insult2 = input("Enter an insult: ")
reaction = input("Enter a reaction ending in -ed: ")
obj4 = input("Enter an object: ")
liquid = input("Enter a liquid: ")
plural_insult2 = input("Enter a weird plural insult: ")

#Story
print("Judy was making her famous " + food1 + ", and was going to pair it with a " + drink1)
print("Rachel was finishing up decorating the living room. She placed the " + obj1 + " as the center piece on the table.")
print("Adam was preparing his coolest hairstyle yet. He called it, the " + Adam_Hair + ".")
print("AJ, Nancy, Liz and Taylor arrived first. As a gift, Taylor brought a " + noun1 + ".")
print("\"I hope you enjoy the " + noun1 + ". Acclaimed Taylor. \"I wasn't sure what to get.\"")
print("\"It's an interesting choice.\" said Judy. \"But we love it!\"")
print("At last, Delores and Chris arrived. Delores brought " + drink2 + " with her.")
print("\"I know it's your fave Jude!\" said Delores. \"We're going to " + verb1 + " our socks off tonight!\"")
print("As everyone mingled, drank and played games, they were all " + adj1 + "about the main event.")
print("Rachel suggested doing a Secret Santa to get everyone in the Christmas cheer.")
print("Everyone got a wacky gift for each other, and couldn't wait to see what their Secret Santa thought of them.")
print("\"Okay " + plural_insult + ", we know what everyone is really here for.\" Yelled Adam.")
print("\"The " + food2 + "?\" Asked Nancy.")
print("\"Well that too.\" Adam replied. \"But let's get the Secret Santa exchange started!\"")
print("Everyone sat around the living room, eager to open their gifts.")
print("Everyone let Taylor go first. Her gift was from Rachel.")
print("As she opened her gift, she saw it was a(n) " + obj2 + ".")
print("Everybody laughed.")
print("As Rachel announced it was her gift, Judy went \"why would anyone ever give that as a gift?!\"")
print("Rachel barked back \"Taylor's creative, she can find a cool way to use it!\"")
print("Next up was Chris. His secret santa was Liz.")
print("He ripped open his gift to find a " + obj3 + ". Everyone laughed again.")
print("\"What am I even gonna do with this?!\" Chris said.")
print("\"Idk figure it out " + insult2 + ".\" Snarked Liz.")
print("One by one everyone opened their gifts, laughing at each one.")
print("Last up was Nancy. Her gift was from Judy.")
print("As she started to open her gift, she " + reaction + ". As she pulled it out, it was a " + obj4 + ".")
print("\"What the hell is this?!\" Nancy yelled, laughing her ass off.")
print("\"Stop it!!\" Laughed Delores. \"You're gonna make me " + drink2 + " myself!\"")
print("As everyone wiped their laughter tears, they thought Secret Santa was a total success.")
print("However, AJ noticed something.")
print("\"Hold on.\" proclaimed AJ. \"There's one more gift!\"")
print("Everyone looked around in confusion everyone received a gift already.")
print("Judy decided to open the gift. In it was Lucy's shit. Shocked, everyone looked at Lucy.")
print("\"Merry Christmas " + plural_insult2 + ".\" Yelled Lucy.")
print("She magically disappeared and reappeared outside in her sleigh, along with her reincats")
print("She road off into the night promising cat shit for all.")
print("Merry Christmas!")