#VARIABLES
verb1 = input("Enter a verb ending in -ing: ")
noun1 = input("Enter a plural noun: ")
adverb1 = input("Enter a singular adverb: ")
person1 = input("Enter an infamous person: ")
verb2 = input("Enter a verb ending in -ed: ")
noun2 = input("Enter a noun: ")
verb3 = input("Enter a verb ending in -ed: ")
clothing1 = input("Enter a piece of clothing: ")
clothing2 = input("Enter another piece of clothing: ")
body_part = input("Enter a body part: ")
noise1 = input("Enter a noise: ")
verb4 = input("Enter a verb: ")
animal1 = input("Enter an animal: ")
noun3 = input("Enter a noun: ")
noun4 = input("Enter a noun: ")
noun5 = input("Enter a noun: ")
noun6 = input("Enter a noun: ")
adj1 = input("Enter an adjective: ")
noun7 = input("Enter a noun: ")
adverb2 = input("Enter an adverb: ")
adj2 = input("Enter an adjective: ")
animal2 = input("Enter an animal: ")
adj3 = input("Enter an adjective: ")
adverb3 = input("Enter an adverb ending in -ly: ")
adverb4 = input("Enter an adverb ending in -ly: ")
person2 = input("Enter a person: ")
animal3 = input("Enter an animal: ")
verb5 = input("Enter a verb ending in -ed: ")
deer1 = input("Enter a person and/or pet: ")
deer2 = input("Enter a person and/or pet: ")
deer3_4 = input("Enter two people and/or pets: ")
deer5 = input("Enter a person and/or pet: ")
deer6 = input("Enter a person and/or pet: ")
deer7_8 = input("Enter two people and/or pets: ")
verb6 = input("Enter a verb: ")
verb7 = input("Enter a verb: ")
noun8 = input("Enter a plural noun: ")
adj4 = input("Enter an adjective: ")
noun9 = input("Enter a plural noun: ")

#STORY
print("'Twas the night before Christmas, with family through the house")
print("Not a Paula was " + verb1 + ", not even a mouse.")
print("The " + noun1 + " were hung by the chimney with " + adverb1)
print("In hope that " + person1 + " soon would be there;")

print("The children were " + verb2 + " all snug in their beds,")
print("While visions of " + noun2 + " " + verb3 + " in their heads;")
print("And Karen in her " + clothing1 + ", and Nancy in her " + clothing2 + ",")
print("Had just settled their " + body_part + "(s) for a long winter's nap,")

print("When out on the lawn there arose such a " + noise1 + ",")
print("Mena sprang from the bed to see what was the matter.")
print("Away to the window Mena " + verb4 + " like a(n) " + animal1 + ",")
print("Tore open the " + noun3 + " and threw up the " + noun4 + ".")

print("The " + noun5 + " on the " + noun6 + " of the new fallen snow")
print("Gave the lustre of " + adj1 + " to the " + noun7 + " below,")
print("When, what to Joyce's " + adverb2 + " eyes should appear,")
print("But a(n) " + adj2 + " sleigh, and eight tiny " + animal2 + "s,")

print("With a(n) " + adj3 + " old driver, so " + adverb3 + " and " + adverb4 + ",")
print("Jeremy knew in a moment it must be " + person2 + ".")
print("More rapid than " + animal3 + " his coursers they came,")
print("And he " + verb5 + ", and shouted, and called them by name: ")

print("\"Now, " + deer1 + "! Now, " + deer2 + "! Now, " + deer3_4 + "!")
print("On, " + deer5 + "! On, " + deer6 + "! On, " + deer7_8 + "!")
print("To the top of the porch! To the top of the wall!")
print("Now " + verb6 + " away! " + verb7 + " away! Dash away all!\"")

print("As " + noun8 + " that before the wild hurricane fly,")
print("When they meet with a " + adj4 + ", mount to the sky;")
print("So up the house-top the coursers they flew,")
print("With the sleigh full of " + noun9 + ", and " + person2 + ".")

print("Merry Christmas to all!")